### ISSUE TITLE
CSIP2 - more direct link to vocabulary would benefit understanding

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#446] opened 2019-05-03 12:05 UTC
CSIP2 

> See also: Content information type declaration http://earkcsip.dilcis.eu/#VocabularyType

could be changed to

> See: http://earkcsip.dilcis.eu/schema/DILCISVocabulariesIP.xml

in order to avoid confusion with Content information type.

**Comment by PhillipTommerholt** [comment] 2019-05-03 12:31
This goes for all the vocabularies, right ? 
I guess the link goes to this placeholder since the more detailed vocabularies and naming of them were not determined at the point? Because I agree that the lnk should lead to the specific vocabulary. Sometimes it is confusing to finde the right vocabulary to find the valid values.

**Comment by karinbredenberg** [comment] 2019-05-03 13:52
In the profile the requirement is linked to its related material via ID's so its the link to the ID of the vocabulary that is used. The Vocabulary has its own short description element in the beginning of the profile and gets an ID there and the requested change is a change in the transformation.

**Comment by PhillipTommerholt** [comment] 2019-05-10 11:33
> In the profile the requirement is linked to its related material via ID's so its the link to the ID of the vocabulary that is used. The Vocabulary has its own short description element in the beginning of the profile and gets an ID there and the requested change is a change in the transformation.

I am not sure I understand this.. 
This is how I experience it.
1) I see the requirement:
![image](https://user-images.githubusercontent.com/15984159/57521160-c81c7780-731f-11e9-86cd-e3aba33eb3f3.png)

2) I click on the link and get the following:
![image](https://user-images.githubusercontent.com/15984159/57521225-f601bc00-731f-11e9-8cfb-40ea4694b983.png)

Since the site is scrolled down I guess I need to click on "the top text" which leads me to:
![image](https://user-images.githubusercontent.com/15984159/57524424-09188a00-7328-11e9-88fd-e9295e9f54d0.png)

So now I have a choice which is not clear..

**Comment by karinbredenberg** [comment] 2019-05-10 15:00
Its not finished, a change in the transformation to web and pdf is needed so it leads to the vcabulary which have been splitted into one vocab per file. But that is not up yet so for now you get errors.

**Comment by carlwilson** [comment] 2020-06-01 04:24
The second set of links now seems to work as intended, this can be closed now.

**Comment by karinbredenberg** [comment] 2020-06-01 09:56
Agree, can be closed it works.

**Closed** 2020-06-16 19:23 UTC
Labels: Feature request, bug
