### ISSUE TITLE
Principle 3.7: Not sure I agree with this principle

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#245] opened 2018-12-17 12:18 UTC
Sorry for raising this concern now, but I'm not sure I totally agree with principle 3.7. It might be a problem of not understanding correctly what the message is but the following sentences are very inconvenient in real-world scenarios:

> The Information Package MUST be implemented by ONLY ONE implementation at any point in time.
> However, it is not reasonable to have multiple implementations available at once as this would lead to unnecessary complexity in developing interoperable tools for creating, processing and managing Information Packages. 

My understanding after reading these sentences is that IT IS NOT RECOMMENDED TO have several VERSIONS of the CSIP (or any of the other packages) in the same implementation at the same time. Well, this is very hard to implement in real-world scenarios. We currently have 10.000.000 AIPs in CSIP version 1.0 and will soon adopt version 2.0.0. There is no way we are going to upgrade all those AIP in a production system.

What will happen is that we will support both versions of the AIP. New AIPs will be created in the new version, and older AIPs will be supported as well, concurrently. And there is no hard in that.

What I'm lacking in the specification is a clear indication of **which version** of the spec is the actual package implementing so that is easy for a running system to parse the package with the right version of the software/library. 

@karinbredenberg and @kuldaraas Any thoughts on this?

**Comment by karinbredenberg** [comment] 2019-05-31 13:09
Moved forward due to need of taking care of the language to make the principle understandable. For now the text remains but its not its own principle. Adding the principle wont break backward compatibility.

**Comment by carlwilson** [comment] 2021-09-24 09:50
Agree and closed, dupe of #178 also closed.

**Closed by carlwilson** 2021-09-24 09:50 UTC
Labels: question, DILCIS review, v2-principles
