### ISSUE TITLE
Relations, segment and parent IP

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#323] opened 2019-03-11 06:46 UTC
Relations between segment and parent IPs should be clarified.

**Comment by carlwilson** [comment] 2019-03-22 09:16
We're dealing with segmented IPs in version 2.1.

**Comment by carlwilson** [comment] 2021-09-24 09:57
Or no we're not now, this hasn't moved enough to publish and #4 records the same concerns. Closing this as a duplicate of #4

**Closed by carlwilson** 2021-09-24 09:57 UTC
Labels: enhancement, Typos and text enhancements, Review comment
